### ISSUE TITLE
Idea private

### ISSUE THREAD

**Issue by marcelloh** [remydt/faces#1]
If the tag `faces:"private"`  is used, I think it shouldn't show an empty value but hide its existence altogether.
(Because private means: "not for your eyes," in my opinion.)

**Comment by remyduthu** [comment]
Hi! Thank you for your feedback. I'm not sure to understand. You want the package to generate another structure (type) without the field?

**Comment by marcelloh** [comment]
When you have  this:
```
// A simple user structure
type User struct {
  Email    string
  Password string `faces:"private"` // The password is part of the user's private face.
}

// Create a user
user := &User{
  Email:    "foo@bar.com",
  Password: "private-password",
}
// Filter the user
faces.Reveal(user, "public")

// Convert the user to JSON
b, _ := json.Marshal(user)

fmt.Println(string(b))
// Output:
// {"email":"foo@bar.com"}
```
Something like that (perhaps it does it already. (Notice that the omitempty is gone)

**Comment by remyduthu** [comment]
The problem here is that this package does not depend on the `json` package. I've used the JSON package in the example but it may be used with any other encoding method.

**Comment by marcelloh** [comment]
Ok, fair enough.
